apiVersion: 1

datasources:
  - name: OAM_DB
    type: mysql
    access: proxy
    url: host.docker.internal:3307
    user: root
    secureJsonData:
      password: gtp_root_pass
    database: oam_portal
    isDefault: true
    editable: true
